---
infra-aws:
  pipeline:
    Cloud Provider:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws_aws-olivier.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws_aws-olivier.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state
      - name: "Keypair public"
        description: "The public SSH key, for SSH access to newly-created instances."
        key: keypair_public
        widget: cy_cred
        type: string
        required: true
        default: "((custom_keypair.ssh_pub))"
      - name: "Keypair private"
        description: "The private SSH key allowing ansible to run playbooks in the Nexus Repository instance via bastion."
        key: keypair_private
        widget: cy_cred
        type: string
        required: true
        default: "((custom_keypair.ssh_prv))"
      # - name: "Bastion Jump URL"
      #   description: "The bastion URL allowing to jump to the Nexus Repository instance in the private VPC (for example admin@52.210.6.203)."
      #   key: bastion_url
      #   widget: simple_text
      #   type: string
      #   required: true
      #   default: "admin@52.210.6.203"

    Stack Configuration:
      - name: "Config repository"
        key: git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:olivier2t/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_github.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: "main"
        required: true

  terraform:
    # VPC:
    #   - name: "VPC ID"
    #     description: "Amazon VPC ID where the Nexus Repository will be created."
    #     key: vpc_id
    #     widget: simple_text
    #     type: string
    #     required: true
    #     default: "vpc-08fe585e0a3fb91c1"

    Nexus:
      - name: "Instance type"
        description: "Instance type for the Nexus Repository."
        key: instance_type
        widget: auto_complete
        type: string
        default: "t3.micro"
        values:
            - t3.nano
            - t3.micro
            - t3.small
            - t3.medium
            - t3.large
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 250